spring.application.name=Egzersiz

# PostgreSQL connection settings
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=fitnessai}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=fitnessai
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Initialize schema before Hibernate runs
spring.sql.init.mode=always

# Fail fast if the database is unreachable
spring.datasource.hikari.initializationFailTimeout=60000
spring.sql.init.continue-on-error=false

#JWT
jwt.secret =TH0ZkLRGQdnm8jDILcKj4k07UVryJZ9y8vXIzAy3vjB

# 15 minutes = 15 * 60 * 1000 = 900000 ms
jwt.expiration=900000

# 7 days = 7 * 24 * 60 * 60 * 1000 = 604800000 ms
jwt.refresh.expiration=604800000

# Gemini API
gemini.api.key=AIzaSyDCgS7ffzNdDe5lDSxsXFPUixZoUDsaIQM